# Site settings
title: Data Science Africa
location: Since 2013
description: "Conference website."
banner: gazzelle.jpg
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.datascienceafrica.org" # the name of your domain
logo_url: img/logo.png
# logo_url: svg/min/logo.svg

email: info@datascienceafrica.org

next:
  url: /dsa2018/
  text: | # From here to "school:"
    <div class="" style="
                        font-weight: bold; 
                        font-size: 18px;

                        ">Kenya: Data Science Africa 2018</div>
    <div>May 31<sup>st</sup>  - June 08<sup>th</sup> 2018</div>
    <div>Nyeri, Kenya</div>

next2:
  url: /dsa2018abuja/
  text: |
    <div class="" style="
                        font-weight: bold; 
                        font-size: 18px;
 
                        ">Nigeria: Data Science Africa 2018</div>
    <div>November 12<sup>th</sup>  - November 16<sup>th</sup> 2018</div>
    <div>Abuja, Nigeria</div>

# Hero
hero:
    # hero_img: hero.jpg
    hero_img: gazzelle.jpg
    hero_img2: chimp.jpg
    hero_title: Data Science
    hero_description: Conference website.

# Contact form
api_token: # Enter API token here

# Testimonials
testimonials:
    testimonials_img: parallax.jpg


# Footer
copyright: Â© 2018 Data Science Africa Conference - All rights reserved
gem: 'kramdown'

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

analytics:
  google:
    tracking_id: UA-80484960-1

video:
  height: 315
  width: 560

# Theme Settings
google_verification:
