# Site settings
title: Data Science | Conference
description: "Conference website."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: img/logo.png
# logo_url: svg/min/logo.svg

# Hero
hero:
    # hero_img: hero.jpg
    hero_img: gazzelle.jpg
    hero_img2: chimp.jpg
    hero_title: Data Science
    hero_description: Conference website.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone:
    emergency:
    email: info@datascienceafrica.org
    address: Von schroeders 273, <br> Viña del mar - Chile

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Von schroeders 273, Viña del mar, Chile
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo


# Footer
copyright: © 2016 Data Science Africa Conference - All rights reserved
gem: 'kramdown'

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics:
google_verification:
